# Generated by Django 5.2 on 2025-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
