# Generated by Django 5.2 on 2025-04-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_c_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
