# Generated by Django 5.2 on 2025-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_c_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events_images/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('canceled', 'Canceled')], default='completed', max_length=50)),
                ('team_or_individual', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
