# Generated by Django 5.2 on 2025-05-01 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0005_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='Enter an 11-digit phone number')]),
        ),
    ]
