# Generated by Django 5.2 on 2025-05-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0006_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
