# Generated by Django 5.2 on 2025-05-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0006_alter_c_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_profile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], default='CUSTOMER', max_length=10),
        ),
    ]
