# Generated by Django 5.2 on 2025-05-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0006_alter_c_profile_phone'),
        ('EventApp', '0007_c_profile_role'),
    ]

    operations = [
    ]
