# Generated by Django 5.2 on 2025-05-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0008_merge_0006_alter_c_profile_phone_0007_c_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='c_profile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], default='CUSTOMER', max_length=10),
        ),
    ]
