# Generated by Django 5.2 on 2025-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0009_alter_c_profile_phone_alter_c_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
