# Generated by Django 5.2 on 2025-05-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0012_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
